# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audit_service_pb2 as audit__service__pb2


class MyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAudit = channel.unary_unary(
                '/api_getway.MyService/CreateAudit',
                request_serializer=audit__service__pb2.AuditRequest.SerializeToString,
                response_deserializer=audit__service__pb2.AuditResponse.FromString,
                )


class MyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAudit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAudit,
                    request_deserializer=audit__service__pb2.AuditRequest.FromString,
                    response_serializer=audit__service__pb2.AuditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api_getway.MyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api_getway.MyService/CreateAudit',
            audit__service__pb2.AuditRequest.SerializeToString,
            audit__service__pb2.AuditResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
